name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

    - name: Clone repo
      uses: actions/checkout@v2

    - name: Start MySQL
      run: sudo /etc/init.d/mysql start

    - name: Create app database and user
      run: |
        mysql -h 127.0.0.1 --port 8888 -uroot -ppassword < db_setup_ci.sql

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Run Tests
      run: bin/ci.sh
